server:
  port: 9411
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: es-server
    

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
  metrics:
    web:
      server:
        auto-time-requests: false    #去除控制台异常

zipkin:
  storage:
    type: elasticsearch
    elasticsearch:
      hosts: http://47.99.88.28:9200
      #      username: elastic
      #      password: changeme
      cluster: elasticsearch
      index: zipkin
      index-shards: 1
      index-replicas: 1
  collector:
    kafka:
      bootstrap-servers: 47.99.88.28:9092
      zookeeper: 47.99.88.28:2181
      topic: zipkin
 


      
eureka:
  client:
    serviceUrl:
      defaultZone:  http://ocp:ocp2019@127.0.0.1:1111/eureka
      #http://130.75.131.241:8761/eureka,http://130.75.131.248:8762/eureka
      #http://134.224.249.33:1111/eureka/  正式库
      #http://134.224.249.33:1111/eureka/  测试库
      #http://127.0.0.1:8761/eureka,http://127.0.0.1:8762/eureka
    registry-fetch-interval-seconds: 5  
    instance-info-replication-interval-seconds: 10      
    
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
#    instance-id: ${spring.application.name}:${docker.ipAddress}:${spring.application.instance_id:${server.port}}
    lease-renewal-interval-in-seconds: 10  #每隔几秒告诉eureka服务器我还存活，用于心跳检测
    lease-expiration-duration-in-seconds: 15 #如果心跳检测一直没有发送，10秒后会从eureka服务器中将此服务剔除


logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE