server:
  port: 1113
management:
  security:
    enabled: false   
eureka:
  server:
    enable-self-preservation: true    #关闭服务器自我保护，客户端心跳检测15分钟内错误达到80%服务会保护，导致别人还认为是好用的服务
    eviction-interval-timer-in-ms: 15000 #5秒将客户端剔除的服务在服务注册列表中剔除
  client: 
    register-with-eureka: true  #false:不作为一个客户端注册到注册中心
    fetch-registry: true      #为true时，可以启动，但报异常：Cannot execute request on any known server
    serviceUrl:
      defaultZone: http://ocp:ocp2019@eureka1:1111/eureka,http://ocp:ocp2019@eureka2:1112/eureka,http://ocp:ocp2019@eureka3:1113/eureka
  instance:
    hostname: eureka3
    appname: eureka-server 
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
    lease-renewal-interval-in-seconds: 10    # 续约更新时间间隔（默认30秒）
    lease-expiration-duration-in-seconds: 30 # 续约到期时间（默认90秒）
logging:
  level:
    root: INFO
    com.open.capacity: INFO    
    org.springframework.web: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE